### ISSUE TITLE
Add JSONPath extraction

### ISSUE THREAD

**Issue by suntong** [JsonCSharpClassGenerator/JsonCSharpClassGenerator#15]
Add extraction support for [JSONPath expressions](http://goessner.net/articles/JsonPath/index.html)

**Comment by suntong** [comment]
Hi @sabarnett, 

What would you think that I/we add JSONPath extraction support into JsonCSharpClassGenerator? 

I know that it is a [scope creep](https://en.wikipedia.org/wiki/Scope_creep) that is way beyond the what JsonCSharpClassGenerator stands for, so I think I'd better ask your opinion first. 

The reason I'm asking is that I'm doing JSONPath extraction all day, but so far I'm relying on some online tools to do that. Having added buttons to beautify/compact the JSON string, the next thing that I want to enhance is my daily task of the JSONPath extraction. Thus my daily task could be within a single tool. 

However the [scope creep](https://en.wikipedia.org/wiki/Scope_creep) beyond JsonCSharpClassGenerator really concerns me. So what would you say if we spin out a new tools base on the current JsonCSharpClassGenerator, so that we can add the JSONPath extraction functionality, with a proper name that covers both cases, say `JsonToolBox` or whatever you think appropriate. 

By doing so, we can immediately address two issues that you complained about previously 

1. The inclusion of the mono CLI project
1. That extra DLL for just a single label

Because it'll be our own project and we don't need to stay loyal to JsonCSharpClassGenerator any more. 

The second reason that I'm discussing this with you is that, I hope I can get your help for it, as I'm a back-end developer, and front-end GUI is really not my cup of tea (for the simple https://github.com/JsonCSharpClassGenerator/JsonCSharpClassGenerator/issues/14, I made *several* attempts *from scratch* just to make the GUI part works as I'm expecting). 

So what would you say? I can help do the initial git repo creation, and provide all back end code for the functionalities. Most importantly, since the majority of the enhancements to the current JsonCSharpClassGenerator are contributed by you, hope you are willing to step forward to take the leadership of this new project of our own. 

Cheers

**Comment by sabarnett** [comment]
I’m more than happy to collaborate on this. I’m not concerned about scope creep on this as we are, as you point out, creating a tool-set for JSON. 

 

From my point of view, I don’t use JSON much in my day job – it’s pretty much just a mechanism to move stuff from the back-end to the Angular front end. Beyond that I have no real experience of using it in production. So I would need to be led by you on what is useful and what isn’t.

 

Sign me up.

**Comment by suntong** [comment]
Oh, that's a wonderful, wonderful news to me. OK, I'll spin out to a new project, JsonToolset or whatever you think appropriate, and clean up the following two before initial check in.

- The inclusion of the mono CLI project
- That extra DLL for just a single label

So we have a *clean* start. 

As for doing JSONPath extraction, the minimum requirement is an input box and output text area just like the one we have holding the input jason, and the back end code is really minimum. However, to make it nice, I'm thinking we need an extra tab, and change the input box into input drop down combo box to hold recent several entries, but we'll come to that next/later...

Will do and let you know...

**Comment by suntong** [comment]
Closing due to

-  scope creep
- lack of time and
- lack of motivation by now
