### ISSUE TITLE
beautify/compact JSON cursor position problem

### ISSUE THREAD

**Issue by suntong** [JsonCSharpClassGenerator/JsonCSharpClassGenerator#17]
When the button to beautify/compact the JSON string is clicked the cursor ends up in a wired position. 

The JSON string that I tried is in
https://gist.github.com/suntong/f6c0045d01070baaa9d64b47e7f54353

NB, Notepad++ suffers the same problem as well.

**Comment by suntong** [comment]
Hi @sabarnett, 

I was trying to fix this as well when fixing #16, but it turns out that [what I found](https://social.msdn.microsoft.com/Forums/vstudio/en-US/68992a9f-f8f8-46f3-9be9-ff959bf989a5/c-setting-cursor-to-first-character-of-textbox?forum=csharpgeneral):

```C#
 private void button1_Click(object sender, EventArgs e)
    {
      textBox1.Focus();
      textBox1.Select(0, 0);
    }
```

Cannot be applied to EasyScintilla SimpleEditor. 

Do you know how to fix this problem? 
Ok if not, as Notepad++ suffers the same problem as well.

**Comment by sabarnett** [comment]
Not sure what the problem is. I just pulled the latest code and ran it. I always end up with the caret positioned on the first character. What're you seeing that's different or what are you expecting to see?

If it's the line/column number that is odd, that'll be because you need to call UpdateCursorPosition() after you reload the content of the editor. This is what I am seeing after the beautify:

![afterbeautify](https://user-images.githubusercontent.com/21052696/33771802-4d490f6a-dc2a-11e7-83a2-4c1f8705ed92.jpg)

**Comment by sabarnett** [comment]
Might also be useful to know:

`

            // Moves the caret to the start of the document
            edtJson.CurrentPosition = 0;

            // Ensures that the aret is visible on screen
            edtJson.ScrollCaret();

            // Gets the position in the file of the first line
            var startOfFirstLine = edtJson.Lines[0].Position;

            // Gets the position in the file of the tenth line
            var startOfTenthLine = edtJson.Lines[9].Position;

            // So to go to the 6th line, you would
            edtJson.CurrentPosition = edtJson.Lines[5].Position;
            edtJson.ScrollCaret();

            // This is what updates the row/column indicator
            UpdateCursorPosition();
`

**Comment by suntong** [comment]
Oh, I'll try again next Monday to see how exactly to duplicate it (or whether possible at all), and let you know...

**Comment by suntong** [comment]
It appear to be a one-time thing that can't be duplicated. Sorry to take your time @sabarnett. 
Thanks for the follow up -- it is indeed "_useful to know_", :-).
