### ISSUE TITLE
Support System.Text.Json

### ISSUE THREAD

**Issue by Lightczx** [JsonCSharpClassGenerator/JsonCSharpClassGenerator#20]
System.Text.Json uses JsonPropertyName rather than JsonProperty to indicate a json property.

**Comment by suntong** [comment]
TBH, I have to admit that I have no idea what you talk about, but please take a look at 

https://github.com/JsonCSharpClassGenerator/JsonCSharpClassGenerator/wiki/About-the-JsonCSharpClassGenerator-GitHub-Fork-Project

and see if it make sense to you. 

thanks

**Comment by Lightczx** [comment]
Thx，I didn't realize there was a historical problem here.
I'll just fork it and modify it for my own purpose.
