### ISSUE TITLE
Update to .Net 4.5

### ISSUE THREAD

**Issue by sabarnett** [JsonCSharpClassGenerator/JsonCSharpClassGenerator#8]
I've tried to get this code running under .Net 4.5 and it won't run. I get an error telling me that one of the dependencies isn't compatible with this version. I believe this is the added dependency on Mono. May I ask why this was added - it only seems to be used as a command line parser, which seems overkill. 

The only other dependency I can see is for the BetterLinkLabel. Seems odd to depend on a third party library for one control - is it worth replacing this?

My ultimate goal was to incorporate EasyScintilla as the editor for the JSON. It makes a much better editor than a text box and, with the right config, gives me syntax highlighting and line numbers (always useful for those error messages that whinge about error on line xxx.

**Comment by suntong** [comment]
Oh, I was compiling under  .Net 4.5.1 and didn't noticed the problem of the Mono dependency. 

So, yeah, if you don't need that command line parsing functionality, feel free to remove it from the solution. I was thinking that _adding_ is the harder part, and _removing_ is relatively easy. 

Let me know. 

I'll leave the Mono dependency there for now as I know most people have moved to .Net 4.5.1 and even far beyond.

**Comment by sabarnett** [comment]
Very odd. I downloaded the source and loaded in to VS2015. The projects all compile as .Net3.5.

**Comment by suntong** [comment]
Oh, I'll double check...

**Comment by suntong** [comment]
please give it a try @sabarnett.

**Comment by suntong** [comment]
Ops, hold on, it builds fine but can't run. 
Investigating...

**Comment by sabarnett** [comment]
That's what I get. No worries, I can replace mono and the link label with code of my own which, I hope, willl fix it. I would have investigated further myself, but I need to get 'proper' work done! Irritating when your day job gets in the way.

**Comment by suntong** [comment]
Oh. I have no idea what's causing the problem though. If you can fix it, please send in a PR. (I don't mind removing the command line parser feature at all)
Thanks a lot!

**Comment by sabarnett** [comment]
Have a look in the app.config for the UI. You'll see a section called "startup" which lists the runtime versions that are supported. You have two entries, one for V4.0 and one for V2. V2 will not be supported if the target .net version  is 4.5.2. Just remove the v2 entry and it should run again.

I'd also recommend using nuget packages for Netonsoft json - you'll get a newer version and yo won't have to distribute it with the code.

**Comment by suntong** [comment]
Thanks a lot @sabarnett, I'll try to do both, if I can make nuget packages do the upgrade not so automatically, :) opened as #9.
