### ISSUE TITLE
using nuget package management

### ISSUE THREAD

**Issue by suntong** [JsonCSharpClassGenerator/JsonCSharpClassGenerator#9]
if I can make nuget packages do the upgrade not so automatically.

**Comment by sabarnett** [comment]
You need to include the Packages.Config files that were created for each project. It's this file that will allow people to download the source and have Visual Studio restore the packages. You should have three of these; one for each project.

**Comment by suntong** [comment]
Yeah, I was thinking this morning that I've had missed something, and was planning to double-check. 

Thanks for pointing it out @sabarnett what exactly they are.
